### ISSUE TITLE
Security concerns

### ISSUE THREAD

**Issue by any626** [MiguelHuerta88/atm-system#9]
Disclaimer: I'm not an expert.
# Vulnerable to timing attacks:
When comparing hashes one should not use `equals` or `==`.
Authentication should be always be constant time.
Reading info:
https://www.brendanlong.com/timing-attacks-and-usernames.html
http://security.stackexchange.com/questions/96489/can-i-prevent-timing-attacks-with-random-delays

# Salts
Salts should be unique to every user.

# Suggestion
Use a library instead of using your own implementation when possible.

**Comment by any626** [comment]
Looking at the latest java, you can use MessageDigest.isEqual over `equals` and `==` as long as you are using java 1.7 over higher.
Double check please.

**Comment by MiguelHuerta88** [comment]
@any626 thanks for the info. I will rework the whole hashing class. I'll move the salt out of the class and into each customer and store the unique salt value. I will also randomize the salt instead of doing it manually. As for the Java version I'll check if I'm over 1.7 then I'll switch the whole checking if two hashes are equals code to instead use Message Digest isEqual.

Thanks

**Comment by MiguelHuerta88** [comment]
Forgot to close this issue. Code was revised and instead used isEqual function from MessageDigest to compare the hashes.
